### ISSUE TITLE
https://github.com/binocarlos/spawn-args/issues/new

### ISSUE THREAD

**Issue by mingqi** [binocarlos/spawn-args#5]
In document that removequotes options works as below:
```javascript
var args = spawnargs('-port 80 --title "this is a title"', { removequotes: true });
/*
 
    [
        '-port',
        '80',
        '--title',
        '"this is a title"'
    ]
    
*/
```

But it doesn't work after I tested it.  Quotes will be remove only if no space in string e.g replace "this is a title" by "thisisatitle" will be works.

is it a bug or expected result?  In my case I want to remove quotes whatever there is space or not because I trying to parse the string to command line arguments.

**Comment by binocarlos** [comment]
Hi,

The offending line is [here](https://github.com/binocarlos/spawn-args/blob/master/index.js#L70)

[this comment](https://github.com/binocarlos/spawn-args/issues/3#issuecomment-103208370) explains why it will only remove quotes for things without spaces (the answer is that removing quotes from something with spaces becomes 2 arguments to a parser.

e.g.

'hello' -> [hello] (1 arg)
'hello world' -> [hello, world] (2 args)

In your case `-port 80 --title "this is a title"` would become `['-port', '80', '--title', 'this', 'is', 'a', 'title']`

It would be possible to have another option that said 'yes I want multiple options after removing quotes' (you can make a PR I will merge it :-)

**Comment by pdxjohnny** [comment]
I used this to remove the unwanted quotes
```javascript
var args = "-e py --exec \"python -m test\" hello test \"program of programs\"";
var options = { removequotes: true };
args = spawnargs(args, options);
for ( var name in args )
{
  if ( args[name][0] == '\"' && args[name][args[name].length - 1] == '\"' &&
    args[name][0] == '\'' && args[name][args[name].length - 1] == '\'' )
  {
    args[name] = args[name].slice(1, args[name].length - 1);
  }
}
console.log(args);
```
